<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SampleThreads_VB</RootNamespace>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsensys.iIDReaderLibrary.SpcInterfaceControl" Version="2.1.0" />
  </ItemGroup>

</Project>
